# Generated by Django 5.1.4 on 2025-05-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_tag_manga_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='volume',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
