# Generated by Django 5.1.4 on 2025-05-21 06:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_chapter_volume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='thanks',
            field=models.ManyToManyField(blank=True, related_name='thanked_chapters', to=settings.AUTH_USER_MODEL),
        ),
    ]
