# Generated by Django 5.2.1 on 2025-05-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0004_chapter_thanks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manga',
            options={'ordering': ('title',), 'verbose_name': 'Taytl', 'verbose_name_plural': 'Taytlar'},
        ),
        migrations.AlterField(
            model_name='manga',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Davom etmoqda'), ('Completed', "To'liq chiqarilgan"), ('Stopped', 'Bekor qilingan'), ('Paused', "To'xtatilgan"), ('Announced', "E'lon qilingan")], default='Ongoing', max_length=50),
        ),
        migrations.AlterField(
            model_name='manga',
            name='translation_status',
            field=models.CharField(choices=[('Not Translated', 'Tarjima qilinmagan'), ('In Progress', 'Tarjima qilinmoqda'), ('Completed', "Tarjima qibo'lingan"), ('Dropped', "Tashlab qo'yilgan")], default='Not Translated', max_length=50),
        ),
    ]
