# Generated by Django 5.2.1 on 2025-05-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0005_alter_manga_options_alter_manga_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='translation_status',
            field=models.CharField(choices=[('Not Translated', 'Tarjima qilinmagan'), ('In Progress', 'Tarjima qilinmoqda'), ('Completed', 'Tarjima qilingan'), ('Dropped', "Tashlab qo'yilgan")], default='Not Translated', max_length=50),
        ),
    ]
