# Generated by Django 5.2.1 on 2025-05-27 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0007_alter_chapter_options_chapter_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='pdf',
        ),
    ]
