# Generated by Django 5.2.1 on 2025-05-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0008_remove_chapter_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
