# Generated by Django 5.2.1 on 2025-05-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0009_alter_page_page_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_number',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
