# Generated by Django 5.2.1 on 2025-05-27 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0010_alter_page_page_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='chapters/pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
