# Generated by Django 5.2.1 on 2025-05-27 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0011_chapter_pdf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
