services:
  - type: web
    name: mangaland
    env: python
    buildCommand: "./build.sh"
    startCommand: "pipenv run gunicorn conf.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: mangaland.onrender.com
