# Generated by Django 5.1.4 on 2025-05-19 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manga', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reading', 'Читаю'), ('planned', 'В планах'), ('dropped', 'Брошено'), ('completed', 'Прочитано'), ('favorite', 'Любимые'), ('ongoing', 'Продолжается')], default='planned', max_length=15)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.manga')),
            ],
            options={
                'verbose_name': 'Статус чтения',
                'verbose_name_plural': 'Статусы чтения',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmarks', models.ManyToManyField(blank=True, related_name='bookmarked_by', to='manga.manga')),
                ('friends', models.ManyToManyField(blank=True, to='accounts.userprofile')),
                ('reading_list', models.ManyToManyField(blank=True, through='accounts.ReadingStatus', to='manga.manga')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.AddField(
            model_name='readingstatus',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_statuses', to='accounts.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='readingstatus',
            unique_together={('user_profile', 'manga')},
        ),
    ]
