# Generated by Django 5.2.1 on 2025-05-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailverificationcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readingstatus',
            options={'verbose_name': "O'qish holati", 'verbose_name_plural': "O'qish holatlari"},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Profil', 'verbose_name_plural': 'Profillar'},
        ),
        migrations.AlterField(
            model_name='readingstatus',
            name='status',
            field=models.CharField(choices=[('reading', "O'qilyapti"), ('planned', 'Rejalashtirilgan'), ('completed', "O'qib bo'lingan"), ('favorite', "Zo'rlari")], default='planned', max_length=15),
        ),
    ]
