# Generated by Django 5.2.1 on 2025-05-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_readingstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingstatus',
            name='status',
            field=models.CharField(choices=[('reading', "O'qilyapti"), ('planned', 'Rejalashtirilgan'), ('completed', "O'qib bo'lingan"), ('favorite', 'Yoqtirganim')], default='planned', max_length=15),
        ),
    ]
