# Generated by Django 5.2.1 on 2025-05-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_readingstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingstatus',
            name='status',
            field=models.CharField(choices=[('reading', "O'qilyapti"), ('planned', "O'qiyman"), ('completed', "O'qilgan"), ('favorite', 'Yoqtirganim')], default='planned', max_length=15),
        ),
    ]
